### ISSUE TITLE
Signup with GitHub should redirect to web browser and ask the login details and then redirect back to our Mobile app 

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#142]
- RN signup with GitHub redirects to the in-app web view which is not the best user experience as it feels like the mocked GitHub screen. 
- So that's why we are moving to the web browser view of the GitHub login and then the creds will authorize, then from the RDS website it will redirect back to the mobile app.

**Sequence diagram** 

![RDS app login](https://user-images.githubusercontent.com/61110378/199809725-5696de2b-6951-42a7-8c2f-d9da59fd5773.jpg)

**Comment by bajajcodes** [comment]
I want to take this and ETA: 3/10/22

**Comment by bajajcodes** [comment]
> I want to take this and ETA: 3/10/22

ETA: 10/10/22

**Comment by arpit01923** [comment]
I also want to contribute in this repo

**Comment by bajajcodes** [comment]
## Possible Ways to Signin With Github using Deep link
- [Firebae Dynamic Link](https://firebase.google.com/docs/dynamic-links), suggested by @dakshbhardwaj 
- [RN Deep link](https://reactnative.dev/docs/linking#enabling-deep-links)
- [Expo Auth Session](https://docs.expo.dev/versions/latest/sdk/auth-session/)
- Deep linking using react-native-router

## Similar Probblem
- [RN Browser Based Auth With Spotify](https://levelup.gitconnected.com/react-native-implementing-browser-based-authentication-using-expos-authsession-component-ffee25b50ae8)
- [RN Social Login With Github](https://levelup.gitconnected.com/how-to-implement-login-with-github-in-a-react-app-bd3d704c64fc)
- [RN deep link and web link with assoication](https://www.youtube.com/watch?v=rvDq2WMU4mw)
- [doordash.engineering](https://doordash.engineering/2022/01/25/your-deep-links-might-be-broken-web-intents-and-android-12/)

cc: @shreya-mishra

**Comment by shreya-mishra** [comment]
> I also want to contribute in this repo

Hey Sure! 
Let's connect for the same then :)

**Comment by sakshambhatt** [comment]
Hey @shreya-mishra, taking this up. ETA for this will be EoD of 21st Nov!

**Comment by sakshambhatt** [comment]
Steps:
- [x] Understanding deeplinking: Not fit for our use case
- [ ] implementing deeplinking in RN
- [x] Opening a specific URL in browser
- [ ] Getting a payload from the page in browser to fire and intent
- [ ] Intent should goto a specific screen in mobile app and sign in the user

**Comment by sakshambhatt** [comment]
## Why the scope should change?
#### Why are we changing the existing flow:

RN auth with GitHub redirects to the in-app web view which is not the best user experience as it feels like the mocked GitHub screen.

#### Issues with deeplinking approach:

1. Security: We make an API call which fetches user data. Once the flow is implemented as is, the call will be made in browser and the data of its response will be a part of the deep-link. Which is not a good thing to do as one should not send any sensitive info in deeplink. [[https://reactnative.dev/docs/security#authentication-and-deep-linking](https://reactnative.dev/docs/security#authentication-and-deep-linking)]
2. Poor UX: This would not make the user experience much better, because the environment will change unnecessarily. In any app they use custom-tabs or SFSafariViewController which keeps the user from leaving the app environment.
3. Going to the RDS site and then signing in to Github is also excessive and not very good in terms of UX. Sometimes, after logging in the Webview does not close, and sometimes there is a delay in setting the AuthContext.

#### Solution: Auth2 with github in RN:

1. If we do want to improve the UX, then why not do it the standard way, have better security and better UX at the same time?
[[https://www.npmjs.com/package/react-native-app-auth](https://www.npmjs.com/package/react-native-app-auth)] is suggested in RN docs. And it uses PKCE [[https://www.oauth.com/oauth2-servers/pkce/](https://www.oauth.com/oauth2-servers/pkce/)], so it will be much more secure. 
2. Our app will hold the auth token returned by github for RDS, and would become an independent client in and of itself, instead of being coupled to website. This would improve the UX considerably because a social sign-in with custom tabs is very common.
3. I need to try this out once, and we can start working on integrating this with our app.

**Comment by sakshambhatt** [comment]
Reference: Login flow in website
![image](https://user-images.githubusercontent.com/33225002/203200726-d661f19f-b15d-4327-ad9b-6a72ffd661a4.png)

**Comment by sakshambhatt** [comment]
Sign in with Github in mobile app:

![image](https://user-images.githubusercontent.com/33225002/203209882-793dbc0f-fe5f-441a-ad26-35b36bb3bdca.png)

**Comment by shreya-mishra** [comment]
assigned to @lakshayman

**Comment by shreya-mishra** [comment]
will reopen when required
